import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Service Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <SessionProvider>
          <div className="bg-primary w-full overflow-hidden">
            <div className="flex justify-center items-center sm:px-16 px-6">
              <div className="xl:max-w-[1280px] w-full">
                <Header />
                <main className="flex-grow min-h-screen">{children}</main>
                <Toaster/>
                <Footer/>
              </div>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
